version: '3.3'
services:
## NGINX
  nginx:
    hostname: nginx
    image: pkur1/project-fibonacci-nginx:latest ## create tags strategy
    ports: 
      - "80:80"
    mem_limit: 256m
## NGINX WITH REACT
  client:
    hostname: client
    image: pkur1/project-fibonacci-client:latest
    mem_limit: 256m
  ## EXPRESSJS
  api:
    hostname: api
    image: pkur1/project-fibonacci-api:latest
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
      - PG_DATABASE=$PG_DATABASE
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
    mem_limit: 256m
  ## WORKER
  worker:
    hostname: worker
    image: pkur1/project-fibonacci-worker:latest
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    mem_limit: 256m

