version: '3.3'
services:
## NGINX
  web:
    depends_on:
      - client
      - api
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"
## NGINX WITH REACT
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  ## EXPRESSJS
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
  ## WORKER
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  ## POSTGRES
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
  ## REDIS
  redis:
    image: redis:6.2.6

